#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 10 17:59:10 2019

@author: egod
"""
import math
import multiprocessing as mp

def job(q):
    print(mp.process._process_counter)
    print('here is {}'.format(mp.process.current_process().name))
    res = 0
    for i in range(1000):
        res += math.sin(i)
    q.put(res)
    
        
    
if __name__ == '__main__':
    
    q = mp.Queue()
    p1 = mp.process.BaseProcess(name='P1',target=job,args=(q,))
    p2 = mp.process.BaseProcess(name='P2',target=job,args=(q,))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    res1 = q.get()
    res2 = q.get()
    print(res1+res2)