#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  7 18:35:05 2019

@author: egod
"""

from maze_env import Maze
from RL_brain import SarsaL

def update():
    for episode in range(100):
        
        observation = env.reset()
        
        
        while True:
            env.render()
            
            action = RL.choose_action(observation)
            observation_,reward,done = env.step(action)
            action_ = RL.choose_action(observation_)
            
            RL.learn(observation,action,reward,observation_,action_)
            
            observation = observation_
            
            if done:
                break
            
    print('game over')
    env.destroy()
    
if __name__=='__main__':
    env = Maze()
    RL = SarsaL(action_space=list(range(env.n_actions)))
    
    env.after(100,update)
    env.mainloop()        