#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 10 17:39:33 2019

@author: egod
"""

import threading
from queue import Queue
import time
import copy
   
def job(l,q):
    res = sum(l)
    q.put(res)

def normal(l):
    print(sum(l))
 
def multi_thread(data):

    q = Queue()
    threads=[]
    
    for i in range(4):
        t = threading.Thread(target=job,
                             name='T{}'.format(i),
                             args=(copy.copy(data),q),
                             )
        t.start()
        threads.append(t)
    
    for thread in threads:
        thread.join()
        
    total = 0
    for _ in range(4):
        total += q.get()
    
    print(total)
    
if __name__ == '__main__':
    l = list(range(1000000))
    t0 = time.time()
    normal(l*4)
    print('normal time : {}'.format(time.time()-t0))
    t0 = time.time()
    multi_thread(l)
    print('normal time : {}'.format(time.time()-t0))
