#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 10 17:48:13 2019

@author: egod
"""

import threading

def job1():
    global A
    
    for i in range(5):
        A += 1
        print('job1 : {}'.format(A))
        
def job2():
    global A
    
    for i in range(5):
        A += 10
        print('job2 : {}'.format(A))
    
def job3():
    global A,lock
    lock.acquire()
    for i in range(5):
        A += 1
        print('job1 : {}'.format(A))
    lock.release()
    
def job4():
    global A,lock
    lock.acquire()
    for i in range(5):
        A += 10
        print('job1 : {}'.format(A))
    lock.release()
    
if __name__ == '__main__':
    lock = threading.Lock()
    A = 0
    t1 = threading.Thread(target=job1)
    t2 = threading.Thread(target=job2)
    t3 = threading.Thread(target=job3)
    t4 = threading.Thread(target=job4)
    t1.start()
    t2.start()
    t1.join()
    t2.join()
    print('\n')
    A = 0
    t3.start()
    t4.start()
    t3.join()
    t4.join()    